### Torch with CPU Device

In [1]:
import torch

In [2]:
x = torch.tensor([12,5])
print(x)

tensor([12,  5])


In [3]:
# Dimenstion of tensor
print("Dimension of Tensor x:",x.size())

Dimension of Tensor x: torch.Size([2])


In [4]:
# Generate the tensor of all zeros1
x = torch.zeros(3,3)
print("3x3 Zeros Tensor:\n",x)

3x3 Zeros Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [5]:
# Generate the tensor of all ones
x = torch.ones(3,3)
print("3x3 Ones Tensor:\n", x)

3x3 Ones Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [9]:
# Generate the tensor of all random values
x = torch.rand(3,3)
print("3x3 Random Tensor:\n", x)
print("Size of the Tensor:", x.size())

3x3 Random Tensor:
 tensor([[0.3886, 0.7397, 0.0500],
        [0.2022, 0.9109, 0.2022],
        [0.4736, 0.5833, 0.9891]])
Size of the Tensor: torch.Size([3, 3])


In [14]:
# addition without dtype
x = torch.ones(3,3, dtype=torch.double)
y = torch.tensor([[2,1,2], 
                [1,2,3], 
                [2,3,1]], dtype=torch.double)
print(x+y)

tensor([[3., 2., 3.],
        [2., 3., 4.],
        [3., 4., 2.]], dtype=torch.float64)


In [16]:
print("Sum of X + y:\n", torch.add(x,y))

Sum of X + y:
 tensor([[3., 2., 3.],
        [2., 3., 4.],
        [3., 4., 2.]], dtype=torch.float64)


In [19]:
# Generate the empty tensor
res = torch.empty(3,3, dtype=torch.double)
print("Empty Tensor:\n", res)

Empty Tensor:
 tensor([[1.2461e-306, 1.3796e-306, 9.3460e-307],
        [1.2906e-306, 1.7802e-306, 1.1126e-306],
        [8.9010e-307, 9.3461e-307, 3.9179e-317]], dtype=torch.float64)


In [20]:
print("Result Res:\n", torch.add(x,y, out=res))

Result Res:
 tensor([[3., 2., 3.],
        [2., 3., 4.],
        [3., 4., 2.]], dtype=torch.float64)


In [21]:
# Resizing the tensor
x = torch.ones(3,3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [22]:
y = x.view(9)
print(y)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [23]:
z = x.view(-1)
print(z)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])


### Torch with GPU Device

In [25]:
# Define the gpu
device = torch.device('cuda')

In [26]:
# Define the ones tensor
x = torch.ones(3,3, device=device)
print("3x3 Ones Tensor with GPU:\n", x)

3x3 Ones Tensor with GPU:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


In [29]:
# Define the ones tensor with float type
y = torch.ones(3,3, dtype=torch.float)
y = y.to(device)
print("3x3 Ones Tensor with GPU:\n", y)

3x3 Ones Tensor with GPU:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


In [30]:
print(x+y)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], device='cuda:0')


In [32]:
print("Run on CPU:\n:",x.to('cpu'))
print("Run on CPU:\n:",y.to('cpu'))

Run on CPU:
: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Run on CPU:
: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
